In [3]:
import pandas as pd

In [4]:
movies = pd.read_csv("imdb-top-1000.csv")
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

# groupby on single columns

In [7]:
genres = movies.groupby("Genre")

In [8]:
# appling builtin aggregation function on groupby object 
# genres.sum(numeric_only = True)
genres.mean(numeric_only = True)
# genres.max(numeric_only = True)
# genres.min(numeric_only = True)
# genres.std(numeric_only = True)
# genres.var(numeric_only = True)
# genres.count()

# you can apply any groupby function

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [9]:
# find top 3 genres by total earning
genres.sum()[["Gross"]].sort_values("Gross",ascending = False).head(3)

               Gross
Genre
Drama   3.540997e+10
Action  3.263226e+10
Comedy  1.566387e+10

In [5]:
# find top 3 genres by total earning
# another way to solve this Quetion
movies.groupby("Genre")["Gross"].sum().sort_values(ascending = False).head(3)

#this is the best way

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [10]:
# find the genres with highest avg IMDB_rating
movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending = False).head(1)

#this is the best way

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [3]:
# find director with most popularity
movies.groupby("Director")["No_of_Votes"].sum().sort_values(ascending = False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [13]:
# find number of movies done my each actor
movies.groupby("Star1")["Series_Title"].count().sort_values(ascending = False)

Star1
Tom Hanks               12
Robert De Niro          11
Clint Eastwood          10
Al Pacino               10
Humphrey Bogart          9
                        ..
Zbigniew Zamachowski     1
Zooey Deschanel          1
Çetin Tekindor           1
Éric Toledano            1
Aaron Taylor-Johnson     1
Name: Series_Title, Length: 660, dtype: int64

In [5]:
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [10]:
movies.groupby("Released_Year")["Series_Title"].count().sort_values(ascending = False).head(10)

Released_Year
2014    32
2004    31
2009    29
2016    28
2013    28
2001    27
2006    26
2007    26
2015    25
2012    24
Name: Series_Title, dtype: int64